
#--- Constants variables used throughout the project---

NO_OF_PARAMETERS={"courseOffer":6,"register":3,"allot":2,"cancel":2}
REGEX = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
INPUT_ERR="INPUT_DATA_ERROR"
COURSE_FULL_ERR="COURSE_FULL_ERROR"
ACCEPTED="ACCEPTED"
COURSE_CANCELED="COURSE_CANCELED"
CONFIRMED="CONFIRMED"
CANCEL_REJECTED="CANCEL_REJECTED"
CANCEL_ACCEPTED="CANCEL_ACCEPTED"
FILE_PATH_ERROR="FILE_PATH_ERROR"
ALLOT_CONFIRMATION_RESPONSE=["REG-COURSE-VIRAT-DP VIRAT@GMAIL.COM OFFERING-DP-STRIVER DP STRIVER 19082022 CONFIRMED".split()]
ALLOT_CANCEL_RESPONSE=["REG-COURSE-ROHIT-TREE ROHIT@GMAIL.COM OFFERING-TREE-ADITYA TREE ADTIYA 01072021 COURSE_CANCELED".split()]